# Basic Information 
title: I-Min (Ray) Chiu
position: ER physician<br>PhD candidate in CSE<br>
affiliation: Kaohsiung Chang Gung Hospital<br>
email: ray1985@cgmh.org.tw

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: ImRayChiu
description: Ray Chiu github page
canonical: https://imraychiu.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com.tw/citations?user=r1986AEAAAAJ&hl=zh-TW
github_link: //github.com/IMinChiu
linkedin: //www.linkedin.com/in/i-min-chiu-45a789182/
Twitter: https://twitter.com/Ray29750200

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/Logo1124.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
